apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-web-canary
  name: locust-web-canary
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: loc-master-web
    - port: 5557
      targetPort: 5557
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: 5558
      protocol: TCP
      name: loc-master-p2
  selector:
    load-balancer-locust-web-canary: "true"
  sessionAffinity: None
  type: LoadBalancer
