apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-prod
  name: locust-prod
spec:
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
      name: loc-master-web
    - port: 5557
      targetPort: 5557
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: 5558
      protocol: TCP
      name: loc-master-p2
  selector:
    load-balancer-locust-prod: "true"
  sessionAffinity: None
  type: LoadBalancer
